### ISSUE TITLE
v1.3.0 couldn't find "libduktape.so"

### ISSUE THREAD

**Issue by zdongcoding** [cashapp/duktape-android#122]
1.3.0

**Comment by JakeWharton** [comment]
This isn't really enough information to diagnose a problem. Can you supply a sample that reproduces the problem that we can take a look at?

**Comment by zdongcoding** [comment]
main module   :   implementation 'com.squareup.duktape:duktape-android:1.3.0'

E/CrashReport: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.xxxx-WlF14NuE724xe_RyYv5Jqw==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxxx-WlF14NuE724xe_RyYv5Jqw==/lib/arm, /data/app/com.xxx.xxxx-WlF14NuE724xe_RyYv5Jqw==/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libduktape.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1660)
        at com.squareup.duktape.Duktape.<clinit>(Duktape.java:28)
        at com.squareup.duktape.Duktape.create(Duktape.java:36)
        at android.app.Activity.performDestroy(Activity.java:7604)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5033)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5065)
        at android.app.ActivityThread.-wrap6(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by zdongcoding** [comment]
I solved this problem because I could not find armeabi  so

**Comment by vaigunth** [comment]
+1

I'm facing the same error in OnePlus 6 on app start. 
Android version 9.0.

Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/in.zeta.android-_EMQ_0yW6IrN8iZRxGw3Ug==/base.apk"],nativeLibraryDirectories=[/data/app/x.x.x-_EMQ_0yW6IrN8iZRxGw3Ug==/lib/arm64, /data/app/x.x.x-_EMQ_0yW6IrN8iZRxGw3Ug==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libduktape.so"

**Comment by JakeWharton** [comment]
NDK 17 removed our ability to even build for armeabi:

> Note: Historically the NDK supported ARMv5 (armeabi), and 32-bit and 64-bit MIPS, but support for these ABIs was removed in NDK r17.

@vaigunth we build for arm64-v8a so if you get an unsatisfied link error then the libraries probably failed to extract. That is tracked by #28.
